package main

import (
	"time"

	"github.com/alexander-cho/manager/api/internal/database"
	"github.com/google/uuid"
)

// create custom User type
type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
}

// databaseUserToUser converts a database.User type generated by sqlc into a custom User type
// allowing for abstraction and control over the data structure within the app.
func databaseUserToUser(dbUser database.User) User {
	return User{
		ID:        dbUser.ID,
		CreatedAt: dbUser.CreatedAt,
		UpdatedAt: dbUser.UpdatedAt,
		Name:      dbUser.Name,
	}
}
